pipeline {
    agent {
  label 'server-1'
}
    tools {
  maven 'MAVEN_HOME'
}
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
            post {
                success {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
      
    }
}
