pipeline {
    agent {
  label 'server-1'
}
    parameters {
        string defaultValue: 'Sangala', name: 'LAST_NAME'
}
    environment {
        Name = "Sreekanth"
}
    tools {
        maven 'MAVEN_HOME'
}
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
                echo "Hello, $Name ${params.$name}."
            }
        }
        stage('test') {
            parellel {
                stage ('test a') {
                    steps {
                        echo 'this is test a'
                        bat 'mvn test'
                    }
                    stage ('test b') {
                        steps {
                            echo 'this is test b'
                            bat 'mvn test'
                        }
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
          
      
    }
}
