pipeline {
    agent {
        label 'dev-server'
    }

    parameters {
        choice choices: ['dev', 'prod'], name: 'Seleect_envirament'
        }

    environment {
        NAME = "Sreekanth"
    }

    tools {
        maven 'MAVEN_HOME'
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            parallel {
                stage('Test A') {
                    agent {
                        label 'dev-server'
                    }
                    steps {
                        echo 'This is Test A'
                        bat 'mvn test'
                    }
                }
                stage('Test B') {
                    agent {
                        label 'dev-server'
                    }
                    steps {
                        echo 'This is Test B'
                        bat 'mvn test'
                    }
                }
            }
             post {
        success {
            dir ('target/surefire-reports') {
                junit '**/TEST-*.xml'
            }
        }
    }
        }

        stage('Deploy') {
            when {
                expression { params.Seleect_envirament == 'prod' }
            }
            steps {
                echo "Deploying to production environment"
            }
        }
    }

   
}
